# Generated by Django 4.2.28 on 2026-02-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
